<?php
return[
    [
        'title' => 'Villa di Lusso a Roma',
        'price' => 750.00,
        'address' => 'Via Appia Antica, 50, Roma',
        'description' => 'Immersa nella storica città di Roma, questa villa di lusso rappresenta l\'essenza dell\'eleganza e del comfort. Situata in una delle zone più prestigiose, Via Appia Antica, la villa offre un ampio giardino ben curato e una piscina privata, ideale per trascorrere momenti di relax in totale privacy. Gli spazi interni, ampi e luminosi, sono arredati con gusto e dotati di tutte le comodità moderne. Con sei stanze, tre camere da letto e quattro bagni, questa villa è perfetta per famiglie numerose o gruppi di amici in cerca di una lussuosa fuga dalla vita quotidiana. La posizione centrale permette di esplorare facilmente le meraviglie di Roma.',
        'rooms' => 6,
        'beds' => 3,
        'bathrooms' => 4,
        'sqm' => 300,
        'latitude' => 41.8582,
        'longitude' => 12.5165,
        'image' => 'villa_roma.jpg',
        'visible' => 1,
        'slug' => 'villa-di-lusso-a-roma',
        'sponsored' =>0,
    ],
    [
        'title' => 'Appartamento Moderno a Milano',
        'price' => 380.00,
        'address' => 'Via Monte Napoleone, 20, Milano',
        'description' => 'Nel cuore di Milano, lungo la prestigiosa Via Monte Napoleone, questo appartamento moderno rappresenta il massimo della comodità e dello stile. Situato a pochi passi dalle principali attrazioni turistiche e dalle boutique di lusso, l’appartamento offre una vista panoramica sulla città. Con tre stanze ben arredate, due camere da letto e due bagni, è ideale per chi cerca un soggiorno elegante e funzionale nel centro di Milano. Gli spazi interni sono caratterizzati da un design contemporaneo e da finiture di alta qualità, perfetti per vivere il dinamico stile di vita milanese.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 120,
        'latitude' => 45.4687,
        'longitude' => 9.1941,
        'image' => 'appartamento_milano.jpg',
        'visible' => 1,
        'slug' => 'appartamento-moderno-a-milano',
        'sponsored' =>0,
    ],
    [
        'title' => 'Casa Colonica in Toscana',
        'price' => 78.00,
        'address' => 'Strada Provinciale 2, Siena',
        'description' => 'Scopri il fascino rustico della campagna toscana con questa antica casa colonica, situata a Siena. Immersa nel verde delle colline toscane, la casa offre un\'accogliente atmosfera campestre con tre camere da letto e tre bagni, ideale per una vacanza rilassante lontana dal caos cittadino. Gli interni, con elementi tradizionali e dettagli autentici, si fondono perfettamente con il paesaggio circostante. Con ampi spazi esterni e un giardino privato, questa casa colonica è perfetta per famiglie o gruppi in cerca di una fuga tranquilla immersa nella natura.',
        'rooms' => 5,
        'beds' => 2,
        'bathrooms' => 3,
        'sqm' => 200,
        'latitude' => 43.3183,
        'longitude' => 11.3312,
        'image' => 'casa_colonica_toscana.jpg',
        'visible' => 1,
        'slug' => 'casa-colonica-in-toscana',
        'sponsored' =>0,
    ],
    [
        'title' => 'Appartamento Vista Mare a Napoli',
        'price' => 89.00,
        'address' => 'Via Partenope, 30, Napoli',
        'description' => 'Situato lungo la suggestiva Via Partenope, questo appartamento offre una vista mozzafiato sul Golfo di Napoli. Con una posizione privilegiata, consente di godere di spettacolari tramonti e di una vista panoramica sul mare. Gli interni sono arredati con gusto e includono una camera da letto e un bagno, ideali per una coppia in cerca di romanticismo e tranquillità. La posizione centrale consente di esplorare facilmente le meraviglie di Napoli, dalle sue storiche strade alle sue rinomate pizzerie.',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'sqm' => 90,
        'latitude' => 40.8300,
        'longitude' => 14.2473,
        'image' => 'appartamento_napoli.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-mare-a-napoli',
        'sponsored' =>1,
    ],
    [
        'title' => 'Rustico in Campagna',
        'price' => 96.00,
        'address' => 'Contrada Santa Lucia, Bari',
        'description' => 'Immerso nella campagna pugliese, questo rustico rappresenta una fuga perfetta nella natura. Situato a Bari, il rustico offre spazi accoglienti con due camere da letto e due bagni, ideali per una famiglia o un gruppo di amici. L\'atmosfera rustica e gli spazi esterni ampi, comprendenti un giardino e una terrazza, permettono di godere di momenti di relax all\'aria aperta. La posizione tranquilla è perfetta per chi cerca una pausa dal ritmo frenetico della vita quotidiana.',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 160,
        'latitude' => 41.1135,
        'longitude' => 16.8760,
        'image' => 'rustico_bari.jpg',
        'visible' => 1,
        'slug' => 'rustico-in-campagna',
        'sponsored' =>0,
    ],
    [
        'title' => 'Loft Industriale a Torino',
        'price' => 118.00,
        'address' => 'Corso Vittorio Emanuele II, 100, Torino',
        'description' => 'Questo loft dallo stile industriale si trova nel cuore pulsante di Torino, lungo Corso Vittorio Emanuele II. Con un design aperto e luminoso, il loft offre un ambiente moderno e dinamico, perfetto per chi ama l\'architettura contemporanea. Composto da una camera da letto e un bagno, il loft è ideale per coppie o professionisti in cerca di uno spazio unico e funzionale. La posizione centrale consente di esplorare facilmente le attrazioni turistiche e culturali di Torino.',
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 110,
        'latitude' => 45.0661,
        'longitude' => 7.6785,
        'image' => 'loft_torino.jpg',
        'visible' => 1,
        'slug' => 'loft-industriale-a-torino',
        'sponsored' =>0,
    ],
    [
        'title' => 'Trullo Tradizionale in Puglia',
        'price' => 190.00,
        'address' => 'Via Ceglie Messapica, Ostuni',
        'description' => 'Scopri la magia dei trulli pugliesi con questo tradizionale trullo situato a Ostuni. Restaurato con cura, il trullo combina il fascino storico con il comfort moderno. Con due camere da letto e un bagno, è ideale per una piccola famiglia o una coppia in cerca di un\'esperienza unica. Gli spazi esterni, con una piccola area all\'aperto, offrono un\'accogliente atmosfera per godersi il sole e la tranquillità della campagna pugliese.',
        'rooms' => 2,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 80,
        'latitude' => 40.7380,
        'longitude' => 17.5802,
        'image' => 'trullo_ostuni.jpg',
        'visible' => 1,
        'slug' => 'trullo-tradizionale-in-puglia',
        'sponsored' =>1,
    ],
    [
        'title' => 'Attico Panoramico a Genova',
        'price' => 225.00,
        'address' => 'Via XX Settembre, 45, Genova',
        'description' => 'Questo splendido attico situato in Via XX Settembre a Genova offre una terrazza panoramica con vista sul mare, ideale per godersi i tramonti e le serate estive. Con tre camere da letto e due bagni, l\'attico è perfetto per famiglie o gruppi in cerca di un soggiorno lussuoso e rilassante. Gli interni eleganti e spaziosi, insieme alla posizione centrale, permettono di esplorare facilmente le meraviglie storiche e culturali di Genova.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 140,
        'latitude' => 44.4073,
        'longitude' => 8.9339,
        'image' => 'attico_genova.jpg',
        'visible' => 1,
        'slug' => 'attico-panoramico-a-genova',
        'sponsored' =>0,
    ],
    [
        'title' => 'Cottage nelle Dolomiti',
        'price' => 368.00,
        'address' => 'Via Dolomiti, Cortina d\'Ampezzo',
        'description' => 'Questo accogliente cottage situato a Cortina d\'Ampezzo offre una vista spettacolare sulle maestose Dolomiti. Con tre camere da letto e due bagni, il cottage è perfetto per famiglie o gruppi in cerca di un rifugio montano. Gli interni, caldi e invitanti, sono arredati con materiali naturali e offrono un\'accogliente atmosfera dopo una giornata di escursioni. La posizione immersa nella natura è ideale per gli amanti della montagna e delle attività all\'aperto.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 130,
        'latitude' => 46.5405,
        'longitude' => 12.1357,
        'image' => 'cottage_dolomiti.jpg',
        'visible' => 1,
        'slug' => 'cottage-nelle-dolomiti',
        'sponsored' =>1,
    ],
    [
        'title' => 'Appartamento in Centro Storico a Firenze',
        'price' => 96.00,
        'address' => 'Via dei Calzaiuoli, 10, Firenze',
        'description' => 'Nel cuore del centro storico di Firenze, questo elegante appartamento rappresenta una fusione di comfort e cultura. Situato lungo Via dei Calzaiuoli, l\'appartamento offre accesso immediato alle principali attrazioni turistiche e culturali della città. Con due camere da letto e un bagno, è ideale per famiglie o gruppi che desiderano esplorare la storia e l\'arte fiorentina. Gli interni raffinati e la posizione centrale offrono un\'esperienza autentica nella capitale del Rinascimento.',
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'sqm' => 100,
        'latitude' => 43.7713,
        'longitude' => 11.2550,
        'image' => 'appartamento_firenze.jpg',
        'visible' => 1,
        'slug' => 'appartamento-in-centro-storico-a-firenze',
        'sponsored' =>0,
    ],
    [
        'title' => 'Villa con Vigneto in Umbria',
        'price' => 58.00,
        'address' => 'Strada del Sagrantino, Montefalco',
        'description' => 'Questa affascinante villa situata a Montefalco, in Umbria, è immersa tra le colline e i vigneti locali. Con cinque camere da letto e tre bagni, la villa è perfetta per famiglie o gruppi in cerca di una pausa rilassante immersa nella natura. La proprietà comprende un vasto vigneto e spazi esterni ideali per godere del paesaggio circostante. Gli interni eleganti e l\'atmosfera serena offrono un\'esperienza unica di lusso e tranquillità.',
        'rooms' => 5,
        'beds' => 6,
        'bathrooms' => 3,
        'sqm' => 250,
        'latitude' => 42.8958,
        'longitude' => 12.6575,
        'image' => 'villa_umbria.jpg',
        'visible' => 1,
        'slug' => 'villa-con-vigneto-in-umbria',
        'sponsored' =>1,
    ],
    [
        'title' => 'Appartamento vista Colosseo',
        'price' => 280.00,
        'address' => 'Via di San Giovanni in Laterano, 20, Roma',
        'description' => 'Situato in Via di San Giovanni in Laterano, questo appartamento offre una vista spettacolare sul Colosseo, uno dei monumenti più iconici di Roma. Con tre camere da letto e due bagni, l\'appartamento è ideale per famiglie o gruppi che desiderano soggiornare vicino a questa storica attrazione. Gli interni moderni e ben arredati offrono un ambiente confortevole e accogliente, mentre la posizione centrale consente di esplorare facilmente le meraviglie della Città Eterna.',
        'rooms' => 3,
        'beds' => 3,
        'bathrooms' => 2,
        'sqm' => 110,
        'latitude' => 41.8896,
        'longitude' => 12.4974,
        'image' => 'appartamento_colosseo.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-colosseo',
        'sponsored' =>0,
    ],
    [
        'title' => 'Casa di Campagna in Sicilia',
        'price' => 89.00,
        'address' => 'Contrada Ramione, Ragusa',
        'description' => 'Situata a Ragusa, questa affascinante casa di campagna è immersa in un uliveto e agrumeto, offrendo una fuga serena dalla vita urbana. Con quattro camere da letto e due bagni, la casa è perfetta per famiglie o gruppi in cerca di un soggiorno tranquillo in Sicilia. Gli spazi esterni includono un giardino e aree relax all\'aperto, ideali per godere del clima mediterraneo e della bellezza naturale della regione.',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 180,
        'latitude' => 36.9255,
        'longitude' => 14.7300,
        'image' => 'casa_sicilia.jpg',
        'visible' => 1,
        'slug' => 'casa-di-campagna-in-sicilia',
        'sponsored' =>0,
    ],
    [
        'title' => 'Appartamento Vista Lago di Como',
        'price' => 150.00,
        'address' => 'Via per Bellagio, Como',
        'description' => 'Questo elegante appartamento situato a Como offre una vista mozzafiato sul Lago di Como. Con due camere da letto e un bagno, l’appartamento è ideale per una coppia o una piccola famiglia in cerca di una vacanza rilassante con vista panoramica. Gli interni moderni e ben arredati offrono tutto il necessario per un soggiorno confortevole, mentre la terrazza privata permette di godere del magnifico paesaggio lacustre.',
        'rooms' => 2,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 95,
        'latitude' => 45.8532,
        'longitude' => 9.3901,
        'image' => 'casa_como.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-lago-di-como',
        'sponsored' =>1,
    ],
    [
        'title' => 'Appartamento di Lusso a Porta Venezia',
        'price' => 450.00,
        'address' => 'Corso Buenos Aires, 33, Milano',
        'description' => 'Situato nel vivace quartiere di Porta Venezia, questo appartamento di lusso combina comfort e modernità. A pochi passi dai migliori negozi e ristoranti, l\'appartamento offre due camere da letto, due bagni e un ampio soggiorno. Gli interni sono decorati con mobili di design e finiture di alta qualità. La posizione centrale rende facile l\'accesso ai trasporti pubblici e alle principali attrazioni di Milano.',
        'rooms' => 2,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 80,
        'latitude' => 45.4765,
        'longitude' => 9.2032,
        'image' => 'appartamento_porta_venezia.jpg',
        'visible' => 1,
        'slug' => 'appartamento-di-lusso-a-porta-venezia',
        'sponsored' => 0,
    ],
    [
        'title' => 'Loft Moderno a Isola',
        'price' => 400.00,
        'address' => 'Via Carlo Farini, 24, Milano',
        'description' => 'Questo loft moderno si trova nel quartiere alla moda di Isola, noto per i suoi bar e ristoranti trendy. L\'appartamento dispone di un ampio open space con cucina a vista, una camera da letto soppalcata e un bagno moderno. Le grandi finestre permettono l\'ingresso di molta luce naturale, creando un ambiente luminoso e accogliente. La posizione è ideale per chi vuole vivere il dinamico stile di vita milanese.',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'sqm' => 90,
        'latitude' => 45.4888,
        'longitude' => 9.1875,
        'image' => 'loft_isola.jpg',
        'visible' => 1,
        'slug' => 'loft-moderno-a-isola',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento con Terrazza a Navigli',
        'price' => 500.00,
        'address' => 'Ripa di Porta Ticinese, 79, Milano',
        'description' => 'Situato nel cuore dei Navigli, questo appartamento offre una grande terrazza con vista sui canali. Con due camere da letto, due bagni e un soggiorno spazioso, è perfetto per chi ama vivere in un ambiente vivace e artistico. Gli interni sono arredati con stile moderno e funzionale, e la terrazza è arredata con mobili da esterno, ideale per cene all\'aperto. La zona è ben servita dai mezzi pubblici e ricca di negozi e locali.',
        'rooms' => 1,
        'beds' => 1,
        'bathrooms' => 1,
        'sqm' => 40,
        'latitude' => 45.4515,
        'longitude' => 9.1744,
        'image' => 'appartamento_navigli.jpg',
        'visible' => 1,
        'slug' => 'appartamento-con-terrazza-a-navigli',
        'sponsored' => 0,
    ],
    [
        'title' => 'Casa Rustica nel Bosco a Canzo',
        'price' => 150.00,
        'address' => 'Via per la Val Ravella, Canzo, Lombardia',
        'description' => 'Questa casa rustica immersa nel verde dei boschi di Canzo offre un rifugio tranquillo e rilassante lontano dal trambusto della città. Con tre camere da letto, due bagni e un ampio soggiorno con camino, la casa è perfetta per chi ama la natura e la serenità. Gli interni sono arredati in stile rustico con travi a vista e mobili in legno massello. All\'esterno, un ampio giardino e una terrazza offrono spazi ideali per godersi l\'aria fresca e il panorama boschivo. La posizione è perfetta per escursioni e passeggiate nei sentieri circostanti.',
        'rooms' => 4,
        'beds' => 3,
        'bathrooms' => 2,
        'sqm' => 150,
        'latitude' => 45.8574,
        'longitude' => 9.2870,
        'image' => 'casa_rustica_canzo.jpg',
        'visible' => 1,
        'slug' => 'casa-rustica-nel-bosco-a-canzo',
        'sponsored' => 0,
    ],
    [
        'title' => 'Villa Panoramica a Positano',
        'price' => 950.00,
        'address' => 'Via Cristoforo Colombo, 50, Positano, Campania',
        'description' => 'Questa splendida villa offre una vista mozzafiato sulla Costiera Amalfitana. Con cinque camere da letto, quattro bagni e una piscina privata, è l\'ideale per una vacanza di lusso. Gli interni sono decorati in stile mediterraneo con ampie finestre panoramiche.',
        'rooms' => 6,
        'beds' => 5,
        'bathrooms' => 4,
        'sqm' => 250,
        'latitude' => 40.6281,
        'longitude' => 14.4847,
        'image' => 'villa_positano.jpg',
        'visible' => 1,
        'slug' => 'villa-panoramica-a-positano',
        'sponsored' => 0,
    ],
    [
        'title' => 'Casa di Campagna a Perugia',
        'price' => 420.00,
        'address' => 'Strada delle Selvette, 18, Perugia, Umbria',
        'description' => 'Questa casa di campagna offre una vista panoramica sulle colline umbre. Con quattro camere da letto, tre bagni e un grande giardino, è perfetta per famiglie numerose o gruppi di amici. Gli interni sono spaziosi e arredati con mobili rustici.',
        'rooms' => 5,
        'beds' => 4,
        'bathrooms' => 3,
        'sqm' => 180,
        'latitude' => 43.1107,
        'longitude' => 12.3908,
        'image' => 'casa_campagna_perugia.jpg',
        'visible' => 1,
        'slug' => 'casa-di-campagna-a-perugia',
        'sponsored' => 0,
    ],
    [
        'title' => 'Villa con Piscina a Olbia',
        'price' => 700.00,
        'address' => 'Via dei Ginepri, 12, Olbia, Sardegna',
        'description' => 'Questa villa con piscina è situata a pochi minuti dalle spiagge più belle della Costa Smeralda. Con quattro camere da letto, tre bagni e un ampio soggiorno, è ideale per una vacanza di lusso. La piscina privata e il giardino curato offrono il massimo del relax.',
        'rooms' => 5,
        'beds' => 4,
        'bathrooms' => 3,
        'sqm' => 220,
        'latitude' => 40.9236,
        'longitude' => 9.4990,
        'image' => 'villa_olbia.jpg',
        'visible' => 1,
        'slug' => 'villa-con-piscina-a-olbia',
        'sponsored' => 0,
    ],
    [
        'title' => 'Villa Rustica a Verona',
        'price' => 550.00,
        'address' => 'Via dei Colli, 30, Verona, Veneto',
        'description' => 'Immersa nella campagna veronese, questa villa rustica offre un soggiorno tranquillo con vista sulle colline circostanti. Con quattro camere da letto, tre bagni, e un grande giardino con piscina, è l\'ideale per chi cerca un angolo di relax senza allontanarsi troppo dalla città. Gli interni sono arredati con eleganza, combinando elementi tradizionali e moderni.',
        'rooms' => 5,
        'beds' => 4,
        'bathrooms' => 3,
        'sqm' => 250,
        'latitude' => 45.4384,
        'longitude' => 10.9921,
        'image' => 'villa_rustica_verona.jpg',
        'visible' => 1,
        'slug' => 'villa-rustica-a-verona',
        'sponsored' => 0,
    ],
    [
        'title' => 'Chalet di Montagna a Courmayeur',
        'price' => 650.00,
        'address' => 'Via delle Alpi, 22, Courmayeur, Valle d\'Aosta',
        'description' => 'Questo elegante chalet di montagna offre una vista panoramica sulle maestose montagne delle Alpi. Con quattro camere da letto, tre bagni e un accogliente soggiorno con camino, è il luogo ideale per una vacanza rilassante. Il chalet dispone anche di una sauna privata e di un ampio terrazzo per godere del panorama circostante. Situato a pochi minuti dalle piste da sci e dal centro di Courmayeur, combina comfort e praticità.',
        'rooms' => 5,
        'beds' => 4,
        'bathrooms' => 3,
        'sqm' => 200,
        'latitude' => 45.7905,
        'longitude' => 6.9671,
        'image' => 'chalet_courmayeur.jpg',
        'visible' => 1,
        'slug' => 'chalet-di-montagna-a-courmayeur',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento Elegante a Cattolica',
        'price' => 300.00,
        'address' => 'Via Carducci, 14, Cattolica, Emilia-Romagna',
        'description' => 'Questo elegante appartamento si trova a pochi passi dalle splendide spiagge di Cattolica e dal centro città. Completamente ristrutturato, offre due camere da letto, un ampio soggiorno e una cucina moderna. Il balcone privato è ideale per cenare all\'aperto e godere del clima mediterraneo. L\'appartamento è arredato con gusto e dotato di tutti i comfort necessari per una vacanza rilassante.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 85,
        'latitude' => 43.9924,
        'longitude' => 12.6620,
        'image' => 'appartamento_cattolica.jpg',
        'visible' => 1,
        'slug' => 'appartamento-elegante-a-cattolica',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento Moderno a Parma',
        'price' => 270.00,
        'address' => 'Via Garibaldi, 8, Parma, Emilia-Romagna',
        'description' => 'Situato nel cuore di Parma, questo appartamento moderno offre comfort e stile a pochi passi dai principali punti di interesse della città. Con due camere da letto, un ampio soggiorno e una cucina completamente attrezzata, è ideale per famiglie o gruppi di amici. L\'appartamento è arredato con un design contemporaneo e dispone di un balcone privato. Goditi la vita cittadina e la gastronomia locale in una delle città più affascinanti dell\'Emilia-Romagna.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 95,
        'latitude' => 44.8015,
        'longitude' => 10.3279,
        'image' => 'appartamento_parma.jpg',
        'visible' => 1,
        'slug' => 'appartamento-moderno-a-parma',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento Vista Mare a Tropea',
        'price' => 320.00,
        'address' => 'Via Libertà, 12, Tropea, Calabria',
        'description' => 'Situato a pochi passi dalle splendide spiagge di Tropea, questo appartamento offre una vista mozzafiato sul mare e sulla città. Completamente arredato e recentemente ristrutturato, dispone di due camere da letto, un soggiorno luminoso con angolo cottura e un balcone privato dove puoi goderti i tramonti sulla costa. L\'appartamento è ideale per una fuga romantica o una vacanza in famiglia, con facile accesso ai ristoranti e alle attrazioni locali.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 85,
        'latitude' => 38.6895,
        'longitude' => 15.8968,
        'image' => 'appartamento_tropea.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-mare-a-tropea',
        'sponsored' => 0,
    ],
    [
        'title' => 'Villa con Vista Lago a Sirmione',
        'price' => 950.00,
        'address' => 'Via dei Pini, 8, Sirmione, Lombardia',
        'description' => 'Questa splendida villa si affaccia sul Lago di Garda e offre una vista mozzafiato sulle acque cristalline e sui panorami circostanti. Con cinque camere da letto, quattro bagni, un grande soggiorno con camino, e una cucina gourmet, è ideale per famiglie o gruppi che cercano un soggiorno lussuoso e rilassante. La villa dispone anche di una piscina privata, un ampio giardino con area barbecue, e una terrazza panoramica. Situata vicino al centro di Sirmione, è perfetta per esplorare le bellezze del lago e la storicità della zona.',
        'rooms' => 6,
        'beds' => 5,
        'bathrooms' => 4,
        'sqm' => 300,
        'latitude' => 45.4875,
        'longitude' => 10.6194,
        'image' => 'villa_sirmione.jpg',
        'visible' => 1,
        'slug' => 'villa-con-vista-lago-a-sirmione',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento Storico a Venezia',
        'price' => 600.00,
        'address' => 'Campo Santa Maria Formosa, 6, Venezia, Veneto',
        'description' => 'Questo affascinante appartamento situato nel cuore di Venezia offre un\'esperienza autentica con i suoi dettagli storici e decorazioni d\'epoca. Con tre camere da letto, due bagni e un elegante soggiorno con vista su uno dei pittoreschi canali veneziani, l\'appartamento è ideale per famiglie o gruppi di amici. Situato vicino ai principali luoghi di interesse, come Piazza San Marco e il Ponte di Rialto, è perfetto per esplorare la città lagunare.',
        'rooms' => 4,
        'beds' => 3,
        'bathrooms' => 2,
        'sqm' => 130,
        'latitude' => 45.4386,
        'longitude' => 12.3351,
        'image' => 'appartamento_venezia.jpg',
        'visible' => 1,
        'slug' => 'appartamento-storico-a-venezia',
        'sponsored' => 0,
    ],
    [
        'title' => 'Loft Moderno a Trieste',
        'price' => 320.00,
        'address' => 'Via del Teatro Romano, 15, Trieste, Friuli Venezia Giulia',
        'description' => 'Questo elegante loft, situato nel centro di Trieste, combina design moderno con comfort e funzionalità. Con due camere da letto, un bagno e un open space che include soggiorno e cucina, è perfetto per un soggiorno cittadino. Il loft dispone anche di un balcone privato con vista sulla città e sul mare Adriatico. Situato a breve distanza dalle principali attrazioni turistiche, ristoranti e caffè storici di Trieste.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 90,
        'latitude' => 45.6504,
        'longitude' => 13.7768,
        'image' => 'loft_trieste.jpg',
        'visible' => 1,
        'slug' => 'loft-moderno-a-trieste',
        'sponsored' => 0,
    ],
    [
        'title' => 'Appartamento Elegante vicino alla Torre di Pisa',
        'price' => 280.00,
        'address' => 'Via dei Mille, 10, Pisa, Toscana',
        'description' => 'Questo elegante appartamento si trova a pochi passi dalla celebre Torre di Pisa e dal centro storico della città. Completamente ristrutturato e arredato con gusto, l\'appartamento dispone di due camere da letto, un bagno moderno, un soggiorno luminoso con angolo cottura e una piccola terrazza privata. È ideale per famiglie o gruppi che desiderano esplorare Pisa e godere della comodità di un alloggio di alta qualità. La posizione centrale permette di accedere facilmente a ristoranti, negozi e attrazioni turistiche.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 85,
        'latitude' => 43.7228,
        'longitude' => 10.3966,
        'image' => 'appartamento_pisa.jpg',
        'visible' => 1,
        'slug' => 'appartamento-elegante-vicino-alla-torre-di-pisa',
        'sponsored' => 0,
    ]
];