<?php
return[
    [
        'title' => 'Villa di Lusso a Roma',
        'price' => 850000.00,
        'address' => 'Via Appia Antica, 50, Roma',
        'description' => 'Villa di lusso con giardino e piscina.',
        'rooms' => 6,
        'beds' => 3,
        'bathrooms' => 4,
        'sqm' => 300,
        'latitude' => 41.8582,
        'longitude' => 12.5165,
        'image' => 'villa_roma.jpg',
        'visible' => 1,
        'slug' => 'villa-di-lusso-a-roma',
    ],
    [
        'title' => 'Appartamento Moderno a Milano',
        'price' => 320000.00,
        'address' => 'Via Monte Napoleone, 20, Milano',
        'description' => 'Appartamento moderno nel centro di Milano.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 120,
        'latitude' => 45.4687,
        'longitude' => 9.1941,
        'image' => 'appartamento_milano.jpg',
        'visible' => 1,
        'slug' => 'appartamento-moderno-a-milano',
    ],
    [
        'title' => 'Casa Colonica in Toscana',
        'price' => 450000.00,
        'address' => 'Strada Provinciale 2, Siena',
        'description' => 'Antica casa colonica immersa nel verde.',
        'rooms' => 5,
        'beds' => 2,
        'bathrooms' => 3,
        'sqm' => 200,
        'latitude' => 43.3183,
        'longitude' => 11.3312,
        'image' => 'casa_colonica_toscana.jpg',
        'visible' => 1,
        'slug' => 'casa-colonica-in-toscana',
    ],
    [
        'title' => 'Appartamento Vista Mare a Napoli',
        'price' => 280000.00,
        'address' => 'Via Partenope, 30, Napoli',
        'description' => 'Appartamento con vista mozzafiato sul Golfo di Napoli.',
        'rooms' => 2,
        'beds' => 1,
        'bathrooms' => 1,
        'sqm' => 90,
        'latitude' => 40.8300,
        'longitude' => 14.2473,
        'image' => 'appartamento_napoli.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-mare-a-napoli',
    ],
    [
        'title' => 'Rustico in Campagna',
        'price' => 200000.00,
        'address' => 'Contrada Santa Lucia, Bari',
        'description' => 'Rustico immerso nella campagna pugliese.',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 160,
        'latitude' => 41.1135,
        'longitude' => 16.8760,
        'image' => 'rustico_bari.jpg',
        'visible' => 1,
        'slug' => 'rustico-in-campagna',
    ],
    [
        'title' => 'Loft Industriale a Torino',
        'price' => 270000.00,
        'address' => 'Corso Vittorio Emanuele II, 100, Torino',
        'description' => 'Loft dallo stile industriale nel cuore di Torino.',
        'rooms' => 1,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 110,
        'latitude' => 45.0661,
        'longitude' => 7.6785,
        'image' => 'loft_torino.jpg',
        'visible' => 1,
        'slug' => 'loft-industriale-a-torino',
    ],
    [
        'title' => 'Trullo Tradizionale in Puglia',
        'price' => 150000.00,
        'address' => 'Via Ceglie Messapica, Ostuni',
        'description' => 'Trullo tradizionale restaurato con cura.',
        'rooms' => 2,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 80,
        'latitude' => 40.7380,
        'longitude' => 17.5802,
        'image' => 'trullo_ostuni.jpg',
        'visible' => 1,
        'slug' => 'trullo-tradizionale-in-puglia',
    ],
    [
        'title' => 'Attico Panoramico a Genova',
        'price' => 500000.00,
        'address' => 'Via XX Settembre, 45, Genova',
        'description' => 'Attico con terrazza panoramica e vista mare.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 140,
        'latitude' => 44.4073,
        'longitude' => 8.9339,
        'image' => 'attico_genova.jpg',
        'visible' => 1,
        'slug' => 'attico-panoramico-a-genova',
    ],
    [
        'title' => 'Cottage nelle Dolomiti',
        'price' => 350000.00,
        'address' => 'Via Dolomiti, Cortina d\'Ampezzo',
        'description' => 'Accogliente cottage di montagna con vista sulle Dolomiti.',
        'rooms' => 3,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 130,
        'latitude' => 46.5405,
        'longitude' => 12.1357,
        'image' => 'cottage_dolomiti.jpg',
        'visible' => 1,
        'slug' => 'cottage-nelle-dolomiti',
    ],
    [
        'title' => 'Appartamento in Centro Storico a Firenze',
        'price' => 380000.00,
        'address' => 'Via dei Calzaiuoli, 10, Firenze',
        'description' => 'Elegante appartamento nel cuore del centro storico di Firenze.',
        'rooms' => 2,
        'beds' => 3,
        'bathrooms' => 1,
        'sqm' => 100,
        'latitude' => 43.7713,
        'longitude' => 11.2550,
        'image' => 'appartamento_firenze.jpg',
        'visible' => 1,
        'slug' => 'appartamento-in-centro-storico-a-firenze',
    ],
    [
        'title' => 'Villa con Vigneto in Umbria',
        'price' => 650000.00,
        'address' => 'Strada del Sagrantino, Montefalco',
        'description' => 'Villa con vigneto nelle colline umbre.',
        'rooms' => 5,
        'beds' => 6,
        'bathrooms' => 3,
        'sqm' => 250,
        'latitude' => 42.8958,
        'longitude' => 12.6575,
        'image' => 'villa_umbria.jpg',
        'visible' => 1,
        'slug' => 'villa-con-vigneto-in-umbria',
    ],
    [
        'title' => 'Appartamento vicino al Colosseo',
        'price' => 450000.00,
        'address' => 'Via di San Giovanni in Laterano, 20, Roma',
        'description' => 'Appartamento con vista sul Colosseo.',
        'rooms' => 3,
        'beds' => 3,
        'bathrooms' => 2,
        'sqm' => 110,
        'latitude' => 41.8896,
        'longitude' => 12.4974,
        'image' => 'appartamento_colosseo.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vicino-al-colosseo',
    ],
    [
        'title' => 'Casa di Campagna in Sicilia',
        'price' => 230000.00,
        'address' => 'Contrada Ramione, Ragusa',
        'description' => 'Casa di campagna con uliveto e agrumeto.',
        'rooms' => 4,
        'beds' => 2,
        'bathrooms' => 2,
        'sqm' => 180,
        'latitude' => 36.9255,
        'longitude' => 14.7300,
        'image' => 'casa_sicilia.jpg',
        'visible' => 1,
        'slug' => 'casa-di-campagna-in-sicilia',
    ],
    [
        'title' => 'Appartamento Vista Lago di Como',
        'price' => 520000.00,
        'address' => 'Via per Bellagio, Como',
        'description' => 'Appartamento con terrazza e vista lago.',
        'rooms' => 2,
        'beds' => 2,
        'bathrooms' => 1,
        'sqm' => 95,
        'latitude' => 45.8532,
        'longitude' => 9.3901,
        'image' => 'casa_como.jpg',
        'visible' => 1,
        'slug' => 'appartamento-vista-lago-di-como',
    ]
];