<?php
return [
   
   'villa_roma.jpg',
   'appartamento_milano.jpg',
   'casa_colonica_toscana.jpg',
   'appartamento_napoli.jpg',
   'rustico_bari.jpg',
   'loft_torino.jpg',
   'trullo_ostuni.jpg',
   'attico_genova.jpg',
   'cottage_dolomiti.jpg',
   'appartamento_firenze.jpg',
   'villa_umbria.jpg',
   'appartamento_colosseo.jpg',
   'casa_sicilia.jpg',
   'casa_como.jpg',
   'appartamento_porta_venezia.jpg',
   'loft_isola.jpg',
   'appartamento-con-terrazza-a-navigli.jpg',
   'casa_rustica_canzo.jpg',
   'villa_positano.jpg',
   'casa-di-campagna-a-perugia.jpg',
   'villa_olbia.jpg',
   'villa_rustica_verona.jpg',
   'chalet_courmayeur.jpg',
   'appartamento_cattolica.jpg',
   'appartamento_parma.jpg',
   'appartamento_tropea.jpg',
   'villa_sirmione.jpg',
   'appartamento_venezia.jpg',
   'loft_trieste.jpg',
   'appartamento_pisa.jpg'

];
